### ISSUE TITLE
panic: interface conversion: ki.Ki is nil, not *gi.Label [recovered]         panic: interface conversion: ki.Ki is nil, not *gi.Label

### ISSUE THREAD

**Issue by ddkwork** [ddkwork/core#9]
### Describe the bug

assert error in lbl := bt.Parts.Child(lbi).(*Label)

### How to reproduce

no

### Example code

```go
no
```

### Relevant output

```shell
panic: interface conversion: ki.Ki is nil, not *gi.Label [recovered]
        panic: interface conversion: ki.Ki is nil, not *gi.Label

goroutine 52 [running]:
cogentcore.org/core/goosi.HandleRecoverPanic({0x7ff713bec620, 0xc001695140})
        D:/workspace/workspace/core/goosi/recover.go:85 +0x9a
cogentcore.org/core/gi.(*RenderWin).EventLoop.func1()
        D:/workspace/workspace/core/gi/renderwin.go:589 +0x24
panic({0x7ff713bec620?, 0xc001695140?})
        C:/Users/Admin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.windows-amd64/src/runtime/panic.go:770 +0x132
cogentcore.org/core/gi.(*Button).ConfigWidget.func1()
        D:/workspace/workspace/core/gi/button.go:428 +0x285
cogentcore.org/core/gi.(*WidgetBase).ConfigParts(0xc0029cad08, {0xc004f290e0, 0x3, 0x4}, {0xc005803198, 0x1, 0x72?})
        D:/workspace/workspace/core/gi/render.go:289 +0x6f
cogentcore.org/core/gi.(*Button).ConfigWidget(0xc0029cad08)
        D:/workspace/workspace/core/gi/button.go:422 +0x925
cogentcore.org/core/gi.(*Button).SetTextUpdate(0xc0029cad08, {0xc003265280, 0xc})
        D:/workspace/workspace/core/gi/button.go:261 +0x51
cogentcore.org/core/giv.(*StructValue).UpdateWidget(0xc0032c62a0)
        D:/workspace/workspace/core/giv/values.go:374 +0x175
cogentcore.org/core/giv.(*StructValue).ConfigWidget(0xc0032c62a0, {0x7ff7153ee6d0?, 0xc0029cad08?})
        D:/workspace/workspace/core/giv/values.go:391 +0x111
cogentcore.org/core/giv.(*TableView).ConfigRows(0xc000a6c008)
        D:/workspace/workspace/core/giv/tableview.go:423 +0xe09
cogentcore.org/core/giv.(*SliceViewBase).SizeFinal(0xc000a6c008)
        D:/workspace/workspace/core/giv/sliceview.go:2023 +0x171
cogentcore.org/core/giv.(*TableView).SizeFinal(0xc000a6c008)
        D:/workspace/workspace/core/giv/tableview.go:824 +0x1e
cogentcore.org/core/gi.(*Layout).SizeFinalChildren.(*WidgetBase).SizeFinalChildren.func2(0xc000a6c008?, {0x7ff7153f1290?, 0xc000a6c008?}, 0x7ff7129d32db?)
        D:/workspace/workspace/core/gi/layimpl.go:1553 +0x24
cogentcore.org/core/gi.(*WidgetBase).VisibleKidsIter(0x10?, 0x7ff715218348)
        D:/workspace/workspace/core/gi/widget.go:530 +0x144
cogentcore.org/core/gi.(*WidgetBase).SizeFinalChildren(...)
        D:/workspace/workspace/core/gi/layimpl.go:1552
cogentcore.org/core/gi.(*Layout).SizeFinalChildren(0xc000a687c8?)
        D:/workspace/workspace/core/gi/layimpl.go:1567 +0x7a
cogentcore.org/core/gi.(*Layout).SizeFinalLay(0xc000a68008)
        D:/workspace/workspace/core/gi/layimpl.go:1544 +0x78
cogentcore.org/core/gi.(*Layout).SizeFinal(...)
        D:/workspace/workspace/core/gi/layimpl.go:1534
cogentcore.org/core/gi.(*Layout).SizeFinalChildren.(*WidgetBase).SizeFinalChildren.func2(0xc000a68008?, {0x7ff7153edd70?, 0xc000a68008?}, 0x7ff7129d2d0c?)
        D:/workspace/workspace/core/gi/layimpl.go:1553 +0x24
cogentcore.org/core/gi.(*WidgetBase).VisibleKidsIter(0x0?, 0x7ff715218348)
        D:/workspace/workspace/core/gi/widget.go:530 +0x144
cogentcore.org/core/gi.(*WidgetBase).SizeFinalChildren(...)
        D:/workspace/workspace/core/gi/layimpl.go:1552
cogentcore.org/core/gi.(*Layout).SizeFinalChildren(0xc0000c74c8?)
        D:/workspace/workspace/core/gi/layimpl.go:1567 +0x7a
cogentcore.org/core/gi.(*Layout).SizeFinalLay(0xc0000c6d08)
        D:/workspace/workspace/core/gi/layimpl.go:1544 +0x78
cogentcore.org/core/gi.(*Layout).SizeFinal(...)
        D:/workspace/workspace/core/gi/layimpl.go:1534
cogentcore.org/core/gi.(*Layout).SizeFinalChildren.(*WidgetBase).SizeFinalChildren.func2(0xc0000c6d08?, {0x255ec1f7588?, 0xc0000c6d08?}, 0x7ff7129d32db?)
        D:/workspace/workspace/core/gi/layimpl.go:1553 +0x24
cogentcore.org/core/gi.(*WidgetBase).VisibleKidsIter(0x10?, 0x7ff715218348)
        D:/workspace/workspace/core/gi/widget.go:530 +0x144
cogentcore.org/core/gi.(*WidgetBase).SizeFinalChildren(...)
        D:/workspace/workspace/core/gi/layimpl.go:1552
cogentcore.org/core/gi.(*Layout).SizeFinalChildren(0xc0000c47c8?)
        D:/workspace/workspace/core/gi/layimpl.go:1567 +0x7a
cogentcore.org/core/gi.(*Layout).SizeFinalLay(0xc0000c4008)
        D:/workspace/workspace/core/gi/layimpl.go:1544 +0x78
cogentcore.org/core/gi.(*Layout).SizeFinal(...)
        D:/workspace/workspace/core/gi/layimpl.go:1534
cogentcore.org/core/gi.(*Layout).SizeFinalChildren.(*WidgetBase).SizeFinalChildren.func2(0xc0000c4008?, {0x7ff7153ec790?, 0xc0000c4008?}, 0xc0000c4008?)
        D:/workspace/workspace/core/gi/layimpl.go:1553 +0x24
cogentcore.org/core/gi.(*WidgetBase).VisibleKidsIter(0xc000484808?, 0x7ff715218348)
        D:/workspace/workspace/core/gi/widget.go:530 +0x144
cogentcore.org/core/gi.(*WidgetBase).SizeFinalChildren(...)
        D:/workspace/workspace/core/gi/layimpl.go:1552
cogentcore.org/core/gi.(*Layout).SizeFinalChildren(0xc000484fc8?)
        D:/workspace/workspace/core/gi/layimpl.go:1567 +0x7a
cogentcore.org/core/gi.(*Layout).SizeFinalLay(0xc000484808)
        D:/workspace/workspace/core/gi/layimpl.go:1544 +0x78
cogentcore.org/core/gi.(*Layout).SizeFinal(...)
        D:/workspace/workspace/core/gi/layimpl.go:1534
cogentcore.org/core/gi.(*Scene).LayoutScene(0xc000484808)
        D:/workspace/workspace/core/gi/render.go:376 +0x326
cogentcore.org/core/gi.(*Scene).LayoutRenderScene(0xc000484808)
        D:/workspace/workspace/core/gi/render.go:390 +0x18
cogentcore.org/core/gi.(*Scene).DoUpdate(0xc000484808)
        D:/workspace/workspace/core/gi/render.go:459 +0x308
cogentcore.org/core/gi.(*Stage).DoUpdate(0xc000aff448?)
        D:/workspace/workspace/core/gi/stage.go:329 +0x57
cogentcore.org/core/gi.(*StageMgr).UpdateAll(0xc000d4c038)
        D:/workspace/workspace/core/gi/stagemgr.go:258 +0xc5
cogentcore.org/core/gi.(*RenderWin).RenderWindow(0xc000d4c000)
        D:/workspace/workspace/core/gi/renderwin.go:982 +0xd1
cogentcore.org/core/gi.(*RenderWin).HandleWindowEvents(0xc000d4c000, {0x7ff7153d0290, 0xc00529eb60})
        D:/workspace/workspace/core/gi/renderwin.go:651 +0x565
cogentcore.org/core/gi.(*RenderWin).HandleEvent(0xc000d4c000, {0x7ff7153d0290, 0xc00529eb60})
        D:/workspace/workspace/core/gi/renderwin.go:636 +0xe5
cogentcore.org/core/gi.(*RenderWin).EventLoop(0xc000d4c000)
        D:/workspace/workspace/core/gi/renderwin.go:603 +0x125
created by cogentcore.org/core/gi.(*RenderWin).GoStartEventLoop in goroutine 1
        D:/workspace/workspace/core/gi/renderwin.go:557 +0xa5
```

### Platform

macOS

**Comment by ddkwork** [comment]
To-do 删除所有包的非并发安全map，nilaway和切片检查测试，压力测试，模糊测试
